
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tpch'
version: '1.3.0'
require-dbt-version: '>=1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'tpch'

# These configurations specify where dbt should look for different types of files.
# The `models-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

on-run-start:
  - "alter warehouse transforming set warehouse_size=small;"
  - '{{create_udfs()}}' # comment / uncomment this line to build UDFs called in the create_udfs macro
  - "{{ dbt_snow_mask.create_masking_policy('models')}}"

on-run-end:
  - "alter warehouse transforming set warehouse_size=xsmall;"
  - "{{ grant_all_on_schemas(schemas, 'transformer') }}"

vars:
  start_date: '1999-01-01'
  test: 'false' # to trigger runs for unit testing - override in a CLI param in testing job
  fct_order_items: 'mock_source__fct_order_items' # this is a map for unit testing
  dbt_metrics_calendar_model: all_days
  use_force_applying_masking_policy: "True" # dbt snow mask

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  +copy_grants: true
  +persist_docs:
    relation: true
    columns: true
  +grants:
    select: ['transformer']
  tpch:
    +required_docs: true
    +query_tag: clinicaltrial-#1232aa213
    staging:
      +materialized: view
      tpch:
        +required_tests: {"unique.*|not_null": 1}

    marts:
      core:
        materialized: table

snapshots:
  tpch:
    +target_schema: "{% if target.name == 'prod' %}snaps{% else %}{{ target.schema }}{% endif %}"

seeds:
  tpch:
    snowflake_contract_rates:
      +column_types:
        effective_date: DATE
        rate: NUMBER   
